apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: task-tracker-prom
type: Opaque
data:
  postgres-password: eW91cl9wYXNzd29yZA==  # echo -n 'your_password' | base64
  postgres-user: eW91cl91c2VybmFtZQ==       # echo -n 'your_username' | base64