apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-deployment
  namespace: task-tracker-prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-tracker
  template:
    metadata:
      labels:
        app: task-tracker
    spec:
      containers:
        - name: task-tracker
          image: thomaswilson1903/tasktracker:latest
          ports:
            - containerPort: 8080
          env:
            - name: URL_DATA
              value: "jdbc:postgresql://postgres-service:5432/task_tracker"
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 3
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 5
#            timeoutSeconds: 3
#            failureThreshold: 1
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"