apiVersion: v1
kind: Service
metadata:
  name: postgres-service-node-port
  namespace: task-tracker-prom
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432        # Порт внутри кластера
      targetPort: 5432  # Порт контейнера
      nodePort: 30434   # Порт для доступа снаружи (30000-32767)