apiVersion: v1
kind: Service
metadata:
  name: task-tracker-service
  namespace: task-tracker-prom
spec:
  type: NodePort
  selector:
    app: task-tracker
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080